### ISSUE TITLE
Examples doesn't work

### ISSUE THREAD

**Issue by Logarithmus** [esa/pykep#73]
Running Debian 9 x64. I've installed pykep and pygmo using Conda. After trying to start an example I finished getting this error:
![_2018-01-30_02-19-31](https://user-images.githubusercontent.com/29541480/35540117-6d6b56a4-0565-11e8-8b98-70572c395dad.png)

Later I opened another terminal and typed there "ipcluster start":
![_2018-01-30_02-36-31](https://user-images.githubusercontent.com/29541480/35540368-a2758576-0566-11e8-875a-cec1cd4a5aff.png)

Then launched example again and it seemed working at the first sight:
![_2018-01-30_02-41-00](https://user-images.githubusercontent.com/29541480/35540497-33ca6316-0567-11e8-901e-21ac6fee8066.png)

But in reality CPU load was about 0%. So what's wrong with my setup? Maybe I should build everything by myself instead of using Conda?

**Comment by darioizzo** [comment]
I am trying to reproduce here ...

**Comment by darioizzo** [comment]
I am trying to understand what your problem may be. Since you are using py27 pygmo selects for you the ipycluster type of palatalization, hence you need to start a cluster first. This is ok and expected behavior, see https://esa.github.io/pagmo2/docs/python/py_island.html#pygmo.island for what is the default choice according to your environment.

The facts that it later hangs is instead weird. Did you activate the conda environment? From your shell prompt it seems like you did not ... ?

**Comment by Logarithmus** [comment]
What do you mean by "activating the conda environment"? Sorry for stupid question.

**Comment by darioizzo** [comment]
if you use conda, you need to activate conda for the system to pick up the correct paths. Something like https://conda.io/docs/user-guide/tasks/manage-environments.html#activating-an-environment

**Comment by Logarithmus** [comment]
I activated the environment, but nothing changed. I'll try reinstalling everything with Python 3.

**Comment by Logarithmus** [comment]
Removed everything and installed miniconda for python3.6 from scratch. Then installed pygmo, pykep, scipy and matplotlib packages. Finally, it works!
