### ISSUE TITLE
Error installing Pykep  on MacOSX

### ISSUE THREAD

**Issue by tomginsberg** [esa/pykep#90]
I followed all the instructions from [here](https://esa.github.io/pykep/installation.html) 

```
cd pykep
mkdir build
cd build
cmake ../ -DBUILD_PYKEP="ON"  -DPYTHON_EXECUTABLE="/usr/local/bin/python3.7m"
```
But when  I run 
```
sudo make install
```
I get the following error

```
[ 82%] Built target lambert_test
[ 84%] Built target propagate_lagrangian_test
[ 87%] Built target propagate_lagrangian_u_test
[ 89%] Built target propagate_taylor_s_test
pykep/core/CMakeFiles/_core.dir/build.make:82: *** target pattern contains no `%'.  Stop.
make[1]: *** [pykep/core/CMakeFiles/_core.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tomginsberg** [comment]
I think the issue is that make is unable to find boost. Is there some way I can specify the path. 
I attempted to change all occurrences of Boost::python37-NOTFOUND in `build.make` and `link.txt` to` /usr/local/Cellar/boost/1.69.0`, but ran into more errors

**Comment by darioizzo** [comment]
In OSX many things can go wrong. Indeed your issue seems to be that python boost is not found. But your solution is risky to say the least. You need to make cmake find the libraries and header paths when you configure. 

1) How did you install boost? homebrew? conda? manually
2) Which python do you want to use? conda? homebrew? system?
3) what cmake are you using? conda? homebrew?

If you mix things up its likely cmake will not find any of the needed paths.

It is always possible, but not reccomended, to indcate paths manually ...

**Comment by tomginsberg** [comment]
Thanks for the help. I've installed python, cmake and boost all using brew

**Comment by darioizzo** [comment]
ok, then when you configure cmake did you try to set the ```CMAKE_INSTALL_PREFIX``` to ```/usr/local``` which I guess the directory where brew is installed?

can you post the output of the command:
```cmake ../ -DBUILD_PYKEP="ON" -DCMAKE_INSTALL_PREFIX=/usr/local```?

Also its better if you try to seek help in the gitter channel, here it is going to be more difficult.
